"""One-time adaptation of the pinned upstream checkout; do not rerun after editing."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / 'backend'
if (BACKEND / 'ruoyi-admin/src/main/resources/db/demo').exists():
    raise SystemExit('Already adapted. This historical helper must not overwrite the implemented project.')

def edit(path, transform):
    path = BACKEND / path
    path.write_text(transform(path.read_text(encoding='utf-8')), encoding='utf-8')

edit('pom.xml', lambda s: s.replace('<java.version>17</java.version>', '<java.version>21</java.version>')
     .replace('        <module>ruoyi-quartz</module>\n', '').replace('        <module>ruoyi-generator</module>\n', ''))
def admin_pom(s):
    s = s.replace('<groupId>com.mysql</groupId>', '<groupId>org.postgresql</groupId>').replace('<artifactId>mysql-connector-j</artifactId>', '<artifactId>postgresql</artifactId>')
    for module in ('ruoyi-quartz', 'ruoyi-generator'):
        s = re.sub(r'<dependency>\s*<groupId>com.ruoyi</groupId>\s*<artifactId>' + module + r'</artifactId>\s*</dependency>', '', s)
    return s.replace('</dependencies>', '''<dependency><groupId>org.flywaydb</groupId><artifactId>flyway-core</artifactId></dependency>
        <dependency><groupId>org.flywaydb</groupId><artifactId>flyway-database-postgresql</artifactId></dependency>
    </dependencies>''')
edit('ruoyi-admin/pom.xml', admin_pom)
edit('ruoyi-admin/src/main/resources/application.yml', lambda s: s.replace('D:/ruoyi/uploadPath', '${AR_UPLOAD_DIR:./.local/uploads}')
     .replace('port: 8080', 'port: ${AR_PORT:18080}').replace('com.ruoyi: debug', 'com.ruoyi: info')
     .replace('host: localhost', 'host: ${AR_REDIS_HOST:127.0.0.1}').replace('port: 6379', 'port: ${AR_REDIS_PORT:16379}')
     .replace('secret: abcdefghijklmnopqrstuvwxyz', 'secret: ${AR_TOKEN_SECRET}')
     .replace('helperDialect: mysql', 'helperDialect: postgresql').replace('enabled: true', 'enabled: false'))
(BACKEND / 'ruoyi-admin/src/main/resources/application-druid.yml').write_text('''spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    druid:
      master:
        url: ${AR_DATABASE_URL:jdbc:postgresql://127.0.0.1:15432/ar_demo}
        username: ${AR_DATABASE_USER:ar_demo}
        password: ${AR_DATABASE_PASSWORD}
      initialSize: 2
      minIdle: 2
      maxActive: 10
      validationQuery: SELECT 1
      statViewServlet:
        enabled: false
      webStatFilter:
        enabled: false
  flyway:
    locations: classpath:db/demo
    clean-disabled: true
  jackson:
    time-zone: UTC
''', encoding='utf-8')

# Preserve upstream schema shape, but omit destructive DROP and demo accounts.
sql = (BACKEND / 'sql/ry_20260417.sql').read_text(encoding='utf-8')
tables = re.findall(r'create table (\w+)\s*\((.*?)\)\s*engine=.*?;', sql, re.S | re.I)
out = ['-- PostgreSQL baseline derived from pinned RuoYi SQL; no upstream passwords.']
identities = []
for name, body in tables:
    if name.startswith('gen_') or name.startswith('sys_job'):
        continue
    body = re.sub(r"\s+comment\s+'[^']*'", '', body)
    body = re.sub(r'\b(bigint|int|tinyint)\(\d+\)', lambda m: 'smallint' if m[1] == 'tinyint' else m[1], body)
    body = body.replace('datetime', 'timestamp with time zone').replace('longtext', 'text')
    body = re.sub(r'not null\s+auto_increment', 'generated by default as identity', body)
    for match in re.finditer(r'(\w+)\s+bigint\s+generated', body):
        identities.append((name, match[1]))
    out.append(f'CREATE TABLE {name} ({body});')
for line in sql.splitlines():
    # Config and dictionary rows are needed by the original UI/services.
    if re.match(r'insert into sys_(config|dict_type|dict_data)\b', line, re.I):
        out.append(line.replace('sysdate()', 'now()'))
out.append('''
INSERT INTO sys_dept(dept_id,dept_name,parent_id,ancestors,order_num,status) VALUES(100,'AR',0,'0',0,'0');
INSERT INTO sys_role(role_id,role_name,role_key,role_sort,data_scope,status) VALUES(100,'管理员','ar_admin',1,'1','0');
UPDATE sys_config SET config_value='false' WHERE config_key IN ('sys.account.registerUser','sys.account.captchaEnabled');
CREATE UNIQUE INDEX sys_user_name_unique ON sys_user(user_name);
''')
for name, col in identities:
    out.append(f"SELECT setval(pg_get_serial_sequence('{name}','{col}'), GREATEST(COALESCE((SELECT max({col}) FROM {name}),0),100),true);")
migration = BACKEND / 'ruoyi-admin/src/main/resources/db/demo'
migration.mkdir(parents=True, exist_ok=True)
(migration / 'V001__ruoyi_postgresql.sql').write_text('\n'.join(out), encoding='utf-8')
for path in (BACKEND / 'ruoyi-system/src/main/resources/mapper').rglob('*.xml'):
    s = path.read_text(encoding='utf-8').replace('sysdate()', 'now()')
    s = re.sub(r"date_format\(([^,]+),'%Y%m%d'\)", r'cast(\1 as date)', s)
    s = re.sub(r'find_in_set\(([^,]+),\s*([^\)]+)\)', r"cast(\1 as text) = ANY(string_to_array(\2, ','))", s)
    s = re.sub(r'ifnull\(', 'coalesce(', s, flags=re.I)
    path.write_text(s, encoding='utf-8')
print('Adapted pinned checkout. Baseline tables:', len(tables))
