-- PostgreSQL baseline derived from pinned RuoYi SQL; no upstream passwords.
CREATE TABLE sys_dept (
  dept_id           bigint      generated by default as identity,
  parent_id         bigint      default 0,
  ancestors         varchar(50)     default '',
  dept_name         varchar(30)     default '',
  order_num         int          default 0,
  leader            varchar(20)     default null,
  phone             varchar(11)     default null,
  email             varchar(50)     default null,
  status            char(1)         default '0',
  del_flag          char(1)         default '0',
  create_by         varchar(64)     default '',
  create_time 	    timestamp with time zone,
  update_by         varchar(64)     default '',
  update_time       timestamp with time zone,
  primary key (dept_id)
);
CREATE TABLE sys_user (
  user_id           bigint      generated by default as identity,
  dept_id           bigint      default null,
  user_name         varchar(30)     not null,
  nick_name         varchar(30)     not null,
  user_type         varchar(2)      default '00',
  email             varchar(50)     default '',
  phonenumber       varchar(11)     default '',
  sex               char(1)         default '0',
  avatar            varchar(100)    default '',
  password          varchar(100)    default '',
  status            char(1)         default '0',
  del_flag          char(1)         default '0',
  login_ip          varchar(128)    default '',
  login_date        timestamp with time zone,
  pwd_update_date   timestamp with time zone,
  create_by         varchar(64)     default '',
  create_time       timestamp with time zone,
  update_by         varchar(64)     default '',
  update_time       timestamp with time zone,
  remark            varchar(500)    default null,
  primary key (user_id)
);
CREATE TABLE sys_post (
  post_id       bigint      generated by default as identity,
  post_code     varchar(64)     not null,
  post_name     varchar(50)     not null,
  post_sort     int          not null,
  status        char(1)         not null,
  create_by     varchar(64)     default '',
  create_time   timestamp with time zone,
  update_by     varchar(64)     default '',
  update_time   timestamp with time zone,
  remark        varchar(500)    default null,
  primary key (post_id)
);
CREATE TABLE sys_role (
  role_id              bigint      generated by default as identity,
  role_name            varchar(30)     not null,
  role_key             varchar(100)    not null,
  role_sort            int          not null,
  data_scope           char(1)         default '1',
  menu_check_strictly  smallint      default 1,
  dept_check_strictly  smallint      default 1,
  status               char(1)         not null,
  del_flag             char(1)         default '0',
  create_by            varchar(64)     default '',
  create_time          timestamp with time zone,
  update_by            varchar(64)     default '',
  update_time          timestamp with time zone,
  remark               varchar(500)    default null,
  primary key (role_id)
);
CREATE TABLE sys_menu (
  menu_id           bigint      generated by default as identity,
  menu_name         varchar(50)     not null,
  parent_id         bigint      default 0,
  order_num         int          default 0,
  path              varchar(200)    default '',
  component         varchar(255)    default null,
  query             varchar(255)    default null,
  route_name        varchar(50)     default '',
  is_frame          int          default 1,
  is_cache          int          default 0,
  menu_type         char(1)         default '',
  visible           char(1)         default 0,
  status            char(1)         default 0,
  perms             varchar(100)    default null,
  icon              varchar(100)    default '#',
  create_by         varchar(64)     default '',
  create_time       timestamp with time zone,
  update_by         varchar(64)     default '',
  update_time       timestamp with time zone,
  remark            varchar(500)    default '',
  primary key (menu_id)
);
CREATE TABLE sys_user_role (
  user_id   bigint not null,
  role_id   bigint not null,
  primary key(user_id, role_id)
);
CREATE TABLE sys_role_menu (
  role_id   bigint not null,
  menu_id   bigint not null,
  primary key(role_id, menu_id)
);
CREATE TABLE sys_role_dept (
  role_id   bigint not null,
  dept_id   bigint not null,
  primary key(role_id, dept_id)
);
CREATE TABLE sys_user_post (
  user_id   bigint not null,
  post_id   bigint not null,
  primary key (user_id, post_id)
);
CREATE TABLE sys_oper_log (
  oper_id           bigint      generated by default as identity,
  title             varchar(50)     default '',
  business_type     int          default 0,
  method            varchar(200)    default '',
  request_method    varchar(10)     default '',
  operator_type     int          default 0,
  oper_name         varchar(50)     default '',
  dept_name         varchar(50)     default '',
  oper_url          varchar(255)    default '',
  oper_ip           varchar(128)    default '',
  oper_location     varchar(255)    default '',
  oper_param        varchar(2000)   default '',
  json_result       varchar(2000)   default '',
  status            int          default 0,
  error_msg         varchar(2000)   default '',
  oper_time         timestamp with time zone,
  cost_time         bigint      default 0,
  primary key (oper_id)
);
CREATE TABLE sys_dict_type (
  dict_id          bigint      generated by default as identity,
  dict_name        varchar(100)    default '',
  dict_type        varchar(100)    default '',
  status           char(1)         default '0',
  create_by        varchar(64)     default '',
  create_time      timestamp with time zone,
  update_by        varchar(64)     default '',
  update_time      timestamp with time zone,
  remark           varchar(500)    default null,
  primary key (dict_id),
  unique (dict_type)
);
CREATE TABLE sys_dict_data (
  dict_code        bigint      generated by default as identity,
  dict_sort        int          default 0,
  dict_label       varchar(100)    default '',
  dict_value       varchar(100)    default '',
  dict_type        varchar(100)    default '',
  css_class        varchar(100)    default null,
  list_class       varchar(100)    default null,
  is_default       char(1)         default 'N',
  status           char(1)         default '0',
  create_by        varchar(64)     default '',
  create_time      timestamp with time zone,
  update_by        varchar(64)     default '',
  update_time      timestamp with time zone,
  remark           varchar(500)    default null,
  primary key (dict_code)
);
CREATE TABLE sys_config (
  config_id         int          generated by default as identity,
  config_name       varchar(100)    default '',
  config_key        varchar(100)    default '',
  config_value      varchar(500)    default '',
  config_type       char(1)         default 'N',
  create_by         varchar(64)     default '',
  create_time       timestamp with time zone,
  update_by         varchar(64)     default '',
  update_time       timestamp with time zone,
  remark            varchar(500)    default null,
  primary key (config_id)
);
CREATE TABLE sys_logininfor (
  info_id        bigint     generated by default as identity,
  user_name      varchar(50)    default '',
  ipaddr         varchar(128)   default '',
  login_location varchar(255)   default '',
  browser        varchar(50)    default '',
  os             varchar(50)    default '',
  status         char(1)        default '0',
  msg            varchar(255)   default '',
  login_time     timestamp with time zone,
  primary key (info_id)
);
CREATE TABLE sys_notice (
  notice_id         int          generated by default as identity,
  notice_title      varchar(50)     not null,
  notice_type       char(1)         not null,
  notice_content    bytea        default null,
  status            char(1)         default '0',
  create_by         varchar(64)     default '',
  create_time       timestamp with time zone,
  update_by         varchar(64)     default '',
  update_time       timestamp with time zone,
  remark            varchar(255)    default null,
  primary key (notice_id)
);
CREATE TABLE sys_notice_read (
  read_id          bigint       generated by default as identity,
  notice_id        int           not null,
  user_id          bigint       not null,
  read_time        timestamp with time zone         not null,
  primary key (read_id),
  constraint uk_user_notice unique (user_id, notice_id)
);
insert into sys_dict_type values(1,  '用户性别', 'sys_user_sex',        '0', 'admin', now(), '', null, '用户性别列表');
insert into sys_dict_type values(2,  '菜单状态', 'sys_show_hide',       '0', 'admin', now(), '', null, '菜单状态列表');
insert into sys_dict_type values(3,  '系统开关', 'sys_normal_disable',  '0', 'admin', now(), '', null, '系统开关列表');
insert into sys_dict_type values(4,  '任务状态', 'sys_job_status',      '0', 'admin', now(), '', null, '任务状态列表');
insert into sys_dict_type values(5,  '任务分组', 'sys_job_group',       '0', 'admin', now(), '', null, '任务分组列表');
insert into sys_dict_type values(6,  '系统是否', 'sys_yes_no',          '0', 'admin', now(), '', null, '系统是否列表');
insert into sys_dict_type values(7,  '通知类型', 'sys_notice_type',     '0', 'admin', now(), '', null, '通知类型列表');
insert into sys_dict_type values(8,  '通知状态', 'sys_notice_status',   '0', 'admin', now(), '', null, '通知状态列表');
insert into sys_dict_type values(9,  '操作类型', 'sys_oper_type',       '0', 'admin', now(), '', null, '操作类型列表');
insert into sys_dict_type values(10, '系统状态', 'sys_common_status',   '0', 'admin', now(), '', null, '登录状态列表');
insert into sys_dict_data values(1,  1,  '男',       '0',       'sys_user_sex',        '',   '',        'Y', '0', 'admin', now(), '', null, '性别男');
insert into sys_dict_data values(2,  2,  '女',       '1',       'sys_user_sex',        '',   '',        'N', '0', 'admin', now(), '', null, '性别女');
insert into sys_dict_data values(3,  3,  '未知',     '2',       'sys_user_sex',        '',   '',        'N', '0', 'admin', now(), '', null, '性别未知');
insert into sys_dict_data values(4,  1,  '显示',     '0',       'sys_show_hide',       '',   'primary', 'Y', '0', 'admin', now(), '', null, '显示菜单');
insert into sys_dict_data values(5,  2,  '隐藏',     '1',       'sys_show_hide',       '',   'danger',  'N', '0', 'admin', now(), '', null, '隐藏菜单');
insert into sys_dict_data values(6,  1,  '正常',     '0',       'sys_normal_disable',  '',   'primary', 'Y', '0', 'admin', now(), '', null, '正常状态');
insert into sys_dict_data values(7,  2,  '停用',     '1',       'sys_normal_disable',  '',   'danger',  'N', '0', 'admin', now(), '', null, '停用状态');
insert into sys_dict_data values(8,  1,  '正常',     '0',       'sys_job_status',      '',   'primary', 'Y', '0', 'admin', now(), '', null, '正常状态');
insert into sys_dict_data values(9,  2,  '暂停',     '1',       'sys_job_status',      '',   'danger',  'N', '0', 'admin', now(), '', null, '停用状态');
insert into sys_dict_data values(10, 1,  '默认',     'DEFAULT', 'sys_job_group',       '',   '',        'Y', '0', 'admin', now(), '', null, '默认分组');
insert into sys_dict_data values(11, 2,  '系统',     'SYSTEM',  'sys_job_group',       '',   '',        'N', '0', 'admin', now(), '', null, '系统分组');
insert into sys_dict_data values(12, 1,  '是',       'Y',       'sys_yes_no',          '',   'primary', 'Y', '0', 'admin', now(), '', null, '系统默认是');
insert into sys_dict_data values(13, 2,  '否',       'N',       'sys_yes_no',          '',   'danger',  'N', '0', 'admin', now(), '', null, '系统默认否');
insert into sys_dict_data values(14, 1,  '通知',     '1',       'sys_notice_type',     '',   'warning', 'Y', '0', 'admin', now(), '', null, '通知');
insert into sys_dict_data values(15, 2,  '公告',     '2',       'sys_notice_type',     '',   'success', 'N', '0', 'admin', now(), '', null, '公告');
insert into sys_dict_data values(16, 1,  '正常',     '0',       'sys_notice_status',   '',   'primary', 'Y', '0', 'admin', now(), '', null, '正常状态');
insert into sys_dict_data values(17, 2,  '关闭',     '1',       'sys_notice_status',   '',   'danger',  'N', '0', 'admin', now(), '', null, '关闭状态');
insert into sys_dict_data values(18, 99, '其他',     '0',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', now(), '', null, '其他操作');
insert into sys_dict_data values(19, 1,  '新增',     '1',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', now(), '', null, '新增操作');
insert into sys_dict_data values(20, 2,  '修改',     '2',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', now(), '', null, '修改操作');
insert into sys_dict_data values(21, 3,  '删除',     '3',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', now(), '', null, '删除操作');
insert into sys_dict_data values(22, 4,  '授权',     '4',       'sys_oper_type',       '',   'primary', 'N', '0', 'admin', now(), '', null, '授权操作');
insert into sys_dict_data values(23, 5,  '导出',     '5',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', now(), '', null, '导出操作');
insert into sys_dict_data values(24, 6,  '导入',     '6',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', now(), '', null, '导入操作');
insert into sys_dict_data values(25, 7,  '强退',     '7',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', now(), '', null, '强退操作');
insert into sys_dict_data values(26, 8,  '生成代码', '8',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', now(), '', null, '生成操作');
insert into sys_dict_data values(27, 9,  '清空数据', '9',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', now(), '', null, '清空操作');
insert into sys_dict_data values(28, 1,  '成功',     '0',       'sys_common_status',   '',   'primary', 'N', '0', 'admin', now(), '', null, '正常状态');
insert into sys_dict_data values(29, 2,  '失败',     '1',       'sys_common_status',   '',   'danger',  'N', '0', 'admin', now(), '', null, '停用状态');
insert into sys_config values(1, '主框架页-默认皮肤样式名称',     'sys.index.skinName',               'skin-blue',     'Y', 'admin', now(), '', null, '蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow' );
insert into sys_config values(2, '用户管理-账号初始密码',         'sys.user.initPassword',            '123456',        'Y', 'admin', now(), '', null, '初始化密码 123456' );
insert into sys_config values(3, '主框架页-侧边栏主题',           'sys.index.sideTheme',              'theme-dark',    'Y', 'admin', now(), '', null, '深色主题theme-dark，浅色主题theme-light' );
insert into sys_config values(4, '账号自助-验证码开关',           'sys.account.captchaEnabled',       'true',          'Y', 'admin', now(), '', null, '是否开启验证码功能（true开启，false关闭）');
insert into sys_config values(5, '账号自助-是否开启用户注册功能', 'sys.account.registerUser',         'false',         'Y', 'admin', now(), '', null, '是否开启注册用户功能（true开启，false关闭）');
insert into sys_config values(6, '用户登录-黑名单列表',           'sys.login.blackIPList',            '',              'Y', 'admin', now(), '', null, '设置登录IP黑名单限制，多个匹配项以;分隔，支持匹配（*通配、网段）');
insert into sys_config values(7, '用户管理-初始密码修改策略',     'sys.account.initPasswordModify',   '1',             'Y', 'admin', now(), '', null, '0：初始密码修改策略关闭，没有任何提示，1：提醒用户，如果未修改初始密码，则在登录时就会提醒修改密码对话框');
insert into sys_config values(8, '用户管理-账号密码更新周期',     'sys.account.passwordValidateDays', '0',             'Y', 'admin', now(), '', null, '密码更新周期（填写数字，数据初始化值为0不限制，若修改必须为大于0小于365的正整数），如果超过这个周期登录系统时，则在登录时就会提醒修改密码对话框');
insert into sys_config values(9, '用户管理-密码字符范围',         'sys.account.chrtype',              '0',             'Y', 'admin', now(), '', null, '默认任意字符范围，0任意（密码可以输入任意字符），1数字（密码只能为0-9数字），2英文字母（密码只能为a-z和A-Z字母），3字母和数字（密码必须包含字母，数字）,4字母数字和特殊字符（目前支持的特殊字符包括：~!@#$%^&*()-=_+）');

INSERT INTO sys_dept(dept_id,dept_name,parent_id,ancestors,order_num,status) VALUES(100,'AR',0,'0',0,'0');
INSERT INTO sys_role(role_id,role_name,role_key,role_sort,data_scope,status) VALUES(100,'管理员','ar_admin',1,'1','0');
UPDATE sys_config SET config_value='false' WHERE config_key IN ('sys.account.registerUser','sys.account.captchaEnabled');
CREATE UNIQUE INDEX sys_user_name_unique ON sys_user(user_name);

SELECT setval(pg_get_serial_sequence('sys_dept','dept_id'), GREATEST(COALESCE((SELECT max(dept_id) FROM sys_dept),0),100),true);
SELECT setval(pg_get_serial_sequence('sys_user','user_id'), GREATEST(COALESCE((SELECT max(user_id) FROM sys_user),0),100),true);
SELECT setval(pg_get_serial_sequence('sys_post','post_id'), GREATEST(COALESCE((SELECT max(post_id) FROM sys_post),0),100),true);
SELECT setval(pg_get_serial_sequence('sys_role','role_id'), GREATEST(COALESCE((SELECT max(role_id) FROM sys_role),0),100),true);
SELECT setval(pg_get_serial_sequence('sys_menu','menu_id'), GREATEST(COALESCE((SELECT max(menu_id) FROM sys_menu),0),100),true);
SELECT setval(pg_get_serial_sequence('sys_oper_log','oper_id'), GREATEST(COALESCE((SELECT max(oper_id) FROM sys_oper_log),0),100),true);
SELECT setval(pg_get_serial_sequence('sys_dict_type','dict_id'), GREATEST(COALESCE((SELECT max(dict_id) FROM sys_dict_type),0),100),true);
SELECT setval(pg_get_serial_sequence('sys_dict_data','dict_code'), GREATEST(COALESCE((SELECT max(dict_code) FROM sys_dict_data),0),100),true);
SELECT setval(pg_get_serial_sequence('sys_logininfor','info_id'), GREATEST(COALESCE((SELECT max(info_id) FROM sys_logininfor),0),100),true);
SELECT setval(pg_get_serial_sequence('sys_notice_read','read_id'), GREATEST(COALESCE((SELECT max(read_id) FROM sys_notice_read),0),100),true);
INSERT INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,menu_type,visible,status,perms,icon) VALUES
(2000,'管理后台',0,1,'admin',NULL,'M','0','0','','system'),
(2001,'账号管理',2000,2,'accounts','demo/accounts','C','0','0','system:user:list','user'),
(2002,'登录日志',2000,3,'loginlogs','monitor/logininfor/index','C','0','0','monitor:logininfor:list','logininfor'),
(2003,'操作日志',2000,4,'operations','monitor/operlog/index','C','0','0','monitor:operlog:list','form'),
(2004,'日志详情',2003,1,'','','F','0','0','monitor:operlog:query','#');
INSERT INTO sys_role_menu(role_id,menu_id) SELECT 100,menu_id FROM sys_menu;

CREATE INDEX idx_sys_oper_log_bt ON sys_oper_log (business_type);
CREATE INDEX idx_sys_oper_log_s ON sys_oper_log (status);
CREATE INDEX idx_sys_oper_log_ot ON sys_oper_log (oper_time);
CREATE INDEX idx_sys_logininfor_s ON sys_logininfor (status);
CREATE INDEX idx_sys_logininfor_lt ON sys_logininfor (login_time);